name = "TwoParameters"
uuid = "c1ae5a22-cd03-426d-8e7b-ac28392c777f"
version = "0.1.0"
authors = ["zbc"]

[deps]
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"

[strategy]
include_file = "src/TwoParameters.jl"
margin = "NoMargin"
min_timeframe = "1h"
mode = "Sim"
